format = """$username $directory $character"""
right_format = """$git_status $git_branch"""

add_newline = false

[character]
success_symbol = "[>](bold fg)"
error_symbol = "[>](bold black)"

[username]
style_user = "white bold"
style_root = "green bold"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
format = "[$path](bold)"
style = "bold white"
truncation_length = 4

[git_branch]
format = "[$branch](bold cyan)"

[git_status]
format="[$all_status $ahead_behind](bold fg)"
conflicted = "="
up_to_date = ""
ahead = ""
diverged = "󰾞"
behind = ""
untracked = "!${count}"
stashed = "?${count}"
modified = "*${count}"
staged = "+${count}"
renamed = "*${count}"
deleted = "-${count}"
